create database price_grid_db;
use price_grid_db;

CREATE TABLE pricecell (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WIDTH INT,
    HEIGHT INT,
    PRICE DOUBLE,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (24, 36, 239);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (30, 36, 269);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (36, 36, 307);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (48, 36, 377);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (60, 36, 450);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (24, 48, 272);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (30, 48, 312);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (36, 48, 357);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (48, 48, 447);
INSERT INTO pricecell (WIDTH, HEIGHT, PRICE) VALUES (60, 48, 536);

